simplemooc/courses/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('', views.courses, name='index'),
    path('<slug:slug>/', views.details, name='details'),
    path('<slug:slug>/inscricao/', views.enrollment, name='enrollment'),
    path('<slug:slug>/anuncios/', views.announcements, name='announcements'),
    path('<slug:slug>/aulas/', views.show_lessons, name='lessons'),
    path('<slug:slug>/aulas/<int:pk>', views.show_lesson, name='lesson'),
    path('<slug:slug>/materiais/<int:pk>', views.show_material, name='material'),
    path('<slug:slug>/desinscrever/', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:slug>/anuncios/<int:pk>', views.show_announcement, name='show_announcement'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

app_name = 'home'

urlpatterns = [
    path('', include('simplemooc.core.urls'),),
    path('conta/', include('simplemooc.accounts.urls',)),
    path('cursos/', include('simplemooc.courses.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/courses/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from simplemooc.core.mail import send_mail_template
from django.utils import timezone


class CourseManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(models.Q(
            name__icontains=query) |
            models.Q(description__icontains=query))


class Course(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição Simples', blank=True)
    about = models.TextField('Sobre o Curso', blank=True)
    startDate = models.DateField('Data de Ínicio', null=True, blank=True)
    image = models.ImageField(
        'Imagem', upload_to='courses/images', null=True, blank=True)
    createdAt = models.DateTimeField('Criado em', auto_now_add=True)
    updatedAt = models.DateTimeField('Atualizado em', auto_now=True)

    objects = CourseManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('course:details', kwargs={'slug': self.slug})

    def release_lessons(self):
        today = timezone.now().date()
        return self.lessons.filter(release_date_gte=today)

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']



class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name='Curso', related_name='lessons', on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank=True)
    number = models.IntegerField('Número (ordem)', blank=True, default = 0)
    release_date = models.DateField('Data de Liberação', blank=True, null=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.name

    def is_available(self):
        if self.release_date:
            today = timezone.now.date()
            return self.release_date>=today
        return True

    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aulas'
        ordering = ['number']

class Material(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name='Aula', related_name='materials',  on_delete=models.CASCADE)
    name = models.CharField('Nome', max_length=100)
    embed_media = models.TextField('Video embedded', blank=True)
    file = models.FileField(upload_to='lessons/materials', verbose_name='Materiais', blank=True, null=True) 

    def is_embedded(self):
        return bool(self.embed_media)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiais'



class Enrollment(models.Model):

    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Inscrito'),
        (2, 'Cancelado'),
        (3, 'Recusado'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             verbose_name='Usuário', related_name='enrollments', on_delete=models.DO_NOTHING)
    course = models.ForeignKey(
        Course, verbose_name='Curso', related_name='enrollments',  on_delete=models.DO_NOTHING)

    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=0, blank=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def active(self):
        self.status = 1
        self.save()

    def is_subscribe(self):
        return self.status == 1

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (
            ('user', 'course'),
        )

class Announcements(models.Model):
    course = models.ForeignKey(Course, verbose_name='Curso',related_name= 'announcements',on_delete=models.CASCADE)
    tittle = models.CharField('Título', max_length=100)
    content = models.TextField('Conteúdo')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.tittle

    class Meta:
        verbose_name = 'Anúncio'
        verbose_name_plural = 'Anúncios'
        ordering = ['-created_at']

class Comments(models.Model):
    announcements = models.ForeignKey(Announcements, verbose_name='Anúncio', related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuario', related_name='comments', on_delete=models.CASCADE)
    comment = models.TextField('Comentário')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    
    def __str__(self):
        return '{0}_{1}'.format(self.user,self.announcements.pk)

    class Meta:
        verbose_name = 'Comentário'
        verbose_name = 'Comentários'

def post_save_announcement(instance, created, **kwargs):
    subject = "Novo anúncio no Curso {0}".format(instance.course)
    context = {'announcement': instance}
    template_name = 'courses/announcement_mail.html'
    enrollments = Enrollment.objects.filter(course=instance.course, status=1)
    emails=[]
    for enrollment in enrollments:
        emails.append(enrollment.user.email)
    send_mail_template(subject, template_name, context, emails)

models.signals.post_save.connect(post_save_announcement, sender=Announcements, dispatch_uid='post_save_announcement')

simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from django.db import models
from simplemooc.core.mail import send_mail_template
from .models import Comments

class ContactCourse(forms.Form):

    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)

    def send_mail(self, course):
        subject = 'Contato Sobre o curso'+ course.name
        message = 'nome: %(name)s;E-mail: %(email)s;%(message)s'
        context = {'name': self.cleaned_data['name'],
                   'email': self.cleaned_data['email'],
                   'message': self.cleaned_data['message'], }
        message = message % context
        template_name = 'courses/contact_email.html'
        send_mail_template(subject,template_name,  context, [settings.EMAIL_CONTACT])

class CommentForm(forms.ModelForm):


    class Meta:
        model = Comments
        fields = ['comment']

simplemooc/courses/views.py
from typing import ContextManager
from django.shortcuts import render, get_object_or_404, redirect
from .models import Announcements, Course, Enrollment, Lesson, Material
from .forms import CommentForm, ContactCourse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .decorators import enrollment_required


def courses(request):
    courses = Course.objects.all()
    template_name = 'courses/index.html'
    context = {'courses': courses}
    return render(request, template_name, context)


def details(request, slug):

    course = get_object_or_404(Course, slug=slug)
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            form.send_mail(course)
            context['isValid'] = True
            form = ContactCourse()
    else:
        form = ContactCourse()

    context['course'] = course
    context['form'] = form
    template_name = 'courses/details.html'

    return render(request, template_name, context)


@login_required
def enrollment(request, slug):
    course = get_object_or_404(Course, slug=slug)
    enrollment, created = Enrollment.objects.get_or_create(
        user=request.user, course=course)
    if created:
        enrollment.active()
        messages.success(
            request, 'Você foi inscrito no curso {0} com sucesso!'.format(course.name))
    else:
        messages.info(
            request, 'Você já se inscreveu para o curso {0}'.format(course.name))
    return redirect('accounts:dashboard')


@login_required
@enrollment_required
def announcements(request, slug):
    context = {}
    course = request.course
    template_name = 'courses/announcements.html'
    context['course'] = course
    context['announcements'] = course.announcements.all()
    context['enrollments'] = Enrollment.objects.filter(user=request.user)
    return render(request, template_name, context)


@login_required
def undo_enrollment(request, slug):
    context = {}
    course = get_object_or_404(Course, slug=slug)
    enrollment = get_object_or_404(
        Enrollment, user=request.user, course=course)
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request, 'A sua incrição no curso {0} foi cancelada'.format(course))
        return redirect('accounts:dashboard')

    context['course'] = course
    template_name = 'courses/undo_enrollment.html'
    return render(request, template_name, context)


@login_required
@enrollment_required
def show_announcement(request, slug, pk):
    context = {}
    course = request.course
    announcement = get_object_or_404(course.announcements.all(), pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False);
        comment.user = request.user
        comment.announcements = announcement
        comment.save()
        form = CommentForm()

    template_name = 'courses/show_announcements.html'
    context['course'] = course
    context['announcement'] = announcement
    context['form'] = form

    return render(request, template_name, context)

@login_required
@enrollment_required
def show_lessons(request, slug):
    course = request.course
    if request.user.is_staff:
        lessons = course.lessons.all()
    else:
        lessons = course.release_lessons()
    template_name = 'courses/lessons.html'
    context = {'course':course,
                'lessons':lessons}
    return render(request,template_name, context)

@login_required
@enrollment_required
def show_lesson(request, slug, pk):
    course = request.course
    lesson = get_object_or_404(Lesson, pk=pk, course=course)
    template_name = 'courses/lesson.html'
    context = {'course':course,
                'lesson': lesson}
    return render(request, template_name, context)

@login_required
@enrollment_required
def show_material(request, slug, pk):
    course = request.course
    material = get_object_or_404(Material, pk=pk, lesson__course=course)
    lesson = material.lesson
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta material não está disponível!')
        return redirect('course:lesson', slug=course.slug, pk=lesson.pk)
    if not material.is_embedded():
        return redirect(material.file.url)
    template_name = 'courses/material.html'
    context = {'course':course,
            'lesson':lesson,
            'material':material,}
    return render(request, template_name, context)
    

simplemooc/courses/templates/courses/announcement_mail.html
{{ announcement.content|linebreaks }}

simplemooc/courses/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
{% for announcement in announcements %}
<div class="well">
    <h2>
        <a href="{% url 'course:show_announcement' announcement.course.slug announcement.pk %}"> 
            {{ announcement.tittle }}
        </a>
    </h2>
    {{announcement.content|linebreaks}}
    <p>
        <a href="{% url 'course:show_announcement' announcement.course.slug announcement.pk %}#comments" title="">
        <i class="fa fa-comments-o"></i>
        {% with comments_count=announcement.comments.count %}
            {{ comments_count }} Comentário{{comments_count|pluralize}}
        {% endwith %}
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>Não há anúncios</h2>
</div>

{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'course:announcements' course.slug %}">{{ course }}</a></li>
{% endblock %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ course }}
</li>
<li>
    <a href="{% url 'course:lessons' course.slug %}">
        <i class="fa fa-video-camera"></i>
        Aulas e Materiais
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-envelope"></i>
        Anúncios
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-comments"></i>
        Fórum de Dúvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{% url 'course:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}

            <h4> Dúvidas?</h4>
            <p>
                <a href="#contato" tittle="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>

</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if isValid %}
            <p>Formulário enviado com sucesso!</p>
        {% endif %}
        <form action="#contato" class="=pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag}}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorList">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso está disponível na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'course:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'course:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'course:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    {{ lesson.description|linebreaks }}
    <p>
        <h4>Material da Aula</h4>
        <table class="pure-table full">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Ação
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for material in lesson.materials.all %}
                <tr class="{% cycle '' 'pure-table-odd' %}">
                    <td>
                        {{ material }}
                    </td>
                    <td>
                        {% if material.is_embedded %}
                        <a href="{% url 'course:material' course.slug material.pk %}">
                            <i class"fa fa-video-camera"></i>
                            Acessar
                        </a>
                        {% else %}
                        <a target="_blank" href="{{ material.file.url }}">
                            <i class"fa fa-download"></i>
                            Baixar
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

simplemooc/courses/templates/courses/lessons.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'course:lessons' course.slug %}">Aulas</a></li>
{% endblock %}

{% block dashboard_content %}
{% for lesson in lessons %}
<div class="well">
    <h2><a href="{% url 'course:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        {{ lesson.description|truncatewords:'20' }}
        <br />
        <a href=""{% url 'course:lesson' course.slug lesson.pk %}"" title="">
        <i class="fa fa-eye"></i>
        Acessar Aula
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>
        Nenhuma aula disponível.
    </h2>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/material.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'course:lessons' course.slug %}">Aulas</a></li>
    <li>/</li>
    <li><a href="{% url 'course:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
    <li>/</li>
    <li><a href="{% url 'course:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'course:material' course.slug material.pk %}">{{ material }}</a></h2>
    {{ material.embed_media|safe }}
    <p>
        <a href="{% url 'course:lesson' course.slug lesson.pk %}">Voltar</a>
    </p>
</div>
{% endblock %}

simplemooc/courses/templates/courses/show_announcements.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'course:show_announcement' course.slug announcement.pk %}">{{ announcement }}</a></li>
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2>{{ announcement.tittle }}</h2>
        {{ announcement.content|linebreaks }}
    </div>
    <div class="well">
        <h4 id="comments">Comentários
        <a class="fright" href="#add_comment">Comentar</a></h4>
        <hr />
        {% for comment in announcement.comments.all %}
        <p>
            <strong>{{ comment.user }}</strong> disse à {{ comment.created_at|timesince }} atrás: <br />
            {{ comment.comment|linebreaksbr }}
        </p>
        <hr>
        {% empty %}
        <p>
            Nenhum comentário para este anúncio.
        </p>
        {% endfor %}
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" href="#comments" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

simplemooc/courses/templates/courses/undo_enrollment.html
{% extends 'courses/course_dashboard.html' %}

{% block dashboard_content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>Você deseja realmente cancelar a inscrição deste curso?</h3>
    <div class="pure-controls">
        <button type="submit" class="pure-button pure-button-primary">Confirmar</button>
        <a href="{% url 'course:announcements' course.slug %}" class="pure-button">Voltar</a>
    </div>
</form>
{% endblock %}