simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views


app_name = 'accounts'


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:index'), name='logout'),
    path('cadastro/', views.register, name='register'),
    path('editarUsuario/', views.edit, name='edit'),
    path('alterarSenha/', views.edit_password, name='edit_password'),
    path('recuperarSenha/', views.password_reset, name='reset_password'),
    path('confirmarNovaSenha/<str:key>/', views.password_reset_confirm, name='password_reset_confirm'),
]

simplemooc/courses/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('', views.courses, name='index'),
    path('<slug:slug>/', views.details, name='details'),
    path('<slug:slug>/inscricao/', views.enrollment, name='enrollment'),
    path('<slug:slug>/anuncios/', views.announcements, name='announcements'),
    path('<slug:slug>/aulas/', views.show_lessons, name='lessons'),
    path('<slug:slug>/aulas/<int:pk>', views.show_lesson, name='lesson'),
    path('<slug:slug>/materiais/<int:pk>', views.show_material, name='material'),
    path('<slug:slug>/desinscrever/', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:slug>/anuncios/<int:pk>', views.show_announcement, name='show_announcement'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

app_name = 'home'

urlpatterns = [
    path('', include('simplemooc.core.urls'),),
    path('conta/', include('simplemooc.accounts.urls',)),
    path('cursos/', include('simplemooc.courses.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin, UserManager)
from django.conf import settings

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('Nome de Usuario', max_length=30, unique=True,
    validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
            'O nome de Usuário só pode conter letras, números ou os seguintes caracteres: @/./+/-/_', 'invalid')])
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está Ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS =['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class PasswordReset(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.DO_NOTHING)


    key = models.CharField('Chave', max_length=100, unique=True) 
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)


    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Redefinição de Senha'
        verbose_name_plural = 'Redefinições de Senhas'
        ordering = ['-created_at']

simplemooc/accounts/forms.py
from re import template
from django import forms
from django.contrib.auth import get_user_model
from simplemooc.core.mail import send_mail_template
from simplemooc.core.utils import generate_hash_key
from .models import PasswordReset

User = get_user_model()


class RegisterForm(forms.ModelForm):
    email = forms.EmailField(label='E-mail')
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('As senhas devem serem iguais')
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']


class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        print(email)
        user = User.objects.all()[1]
        print(user.email)
        if User.objects.filter(email=email).exists():
            return email
        else:
            raise forms.ValidationError(
                'Nenhum usuário encontrado com este e-mail')

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Simplemooc: Redefinição de senha'
        context = {'reset': reset}
        send_mail_template(subject, template_name, context,
                           [user.email])

simplemooc/accounts/views.py
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth import get_user_model
from simplemooc.accounts.models import PasswordReset
from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from simplemooc.courses.models import Enrollment

User = get_user_model()


@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context ={}
    context['enrollments'] = Enrollment.objects.filter(user=request.user)
    return render(request, template_name, context)


def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        print('entrou')
        form = RegisterForm()
    context = {'form': form}
    return render(request, template_name, context)


@login_required
def edit(request):
    context = {}
    template_name = 'accounts/edit.html'
    if request.method == 'POST':
        form = EditAccountForm(request.POST or None, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)
            context['success'] = True
    else:
        form = EditAccountForm(instance=request.user)
    form = EditAccountForm()
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)


def password_reset(request):
    context = {}
    template_name = 'accounts/password_reset.html'
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True

    context['form'] = form
    return render(request, template_name, context)


def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        print('passou')
        context['success'] = True


    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Bem-vindo, {{ user }}
                </li>
                {% block menu_options %}

                {% my_courses user %}
                <li class="pure-menu-heading">Configurações de Conta</li>
                <li>
                    <a href="{% url 'accounts:edit' %}">
                    <i class="fa fa-cog"></i>
                    Editar Informações
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:edit_password' %}">
                    <i class="fa fa-lock"></i>
                    Editar Senha
                    </a>
                </li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <h2>Meus Cursos</h2>
            {% for enrollment in enrollments %}
            <div class="well">
                <h3>{{ enrollment.course }}
                ({{ enrollment.course.startDate|date:'d/m/Y'|default:'Sem data' }})
                </h3>
                {{ enrollment.course.description|linebreaks }}
                <div class="pure-controls">
                    <a href="{% url 'course:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">Acessar</a>
                    <a href="{% url 'course:undo_enrollment' enrollment.course.slug %}" class="button-error  pure-button">Cancelar</a>
                </div>
            </div>
            {% empty %}
            <aside class="pure-u-1">
                <p>Nenhum curso inscrito</p>
            </aside>
            {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Os dados foram alterados com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-aligned" method="post">
             {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                 
                <div class="pure-control-group">
                    {{ field.label_tag}}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="pure-control-group">
                    
                </div>
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="{% url 'accounts:reset_password' %}" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Um e-mail foi enviando para você com mais detalhes de como criar uma nova senha</p>
        {% else %}
        <h2>Informe seu E-mail</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
        <p>Sua senha foi criada com sucesso</p>
        {% else %}
        <h2>Informe sua nova Senha</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p>Para criar uma nova senha, acesse o link: <a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key %}" title="Link para Criar Nova Senha">Criar Nova Senha</a></p>

simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}